# Generated by Django 3.0.4 on 2020-04-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='subjects',
            new_name='subject',
        ),
    ]
