# Generated by Django 3.0.4 on 2020-04-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_auto_20200402_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='subject',
            new_name='subjects',
        ),
    ]
