# Generated by Django 3.0.4 on 2020-04-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_auto_20200404_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='region',
            field=models.ManyToManyField(to='Report.Region'),
        ),
    ]
