# Generated by Django 3.0.4 on 2020-04-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_auto_20200406_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='region',
            new_name='regions',
        ),
    ]
