# Generated by Django 3.0.4 on 2020-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0005_auto_20200406_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='schools',
            field=models.ManyToManyField(to='Report.School'),
        ),
    ]
