# Generated by Django 3.0.4 on 2020-04-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0006_auto_20200406_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('', '')], max_length=20),
        ),
    ]
