# Generated by Django 3.0.4 on 2020-04-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0007_auto_20200407_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('waja', 'Waja Schools'), ('Emaco', 'Emaco')], max_length=20),
        ),
    ]
