# Generated by Django 3.0.4 on 2020-04-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0008_auto_20200407_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('waja', 'Waja Schools'), ('Emaco', 'Emaco'), ('Kahama_muslim', 'Kahama_muslim')], max_length=20),
        ),
    ]
