# Generated by Django 3.0.4 on 2020-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0009_auto_20200408_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(choices=[('waja', 'Waja Schools'), ('Emaco', 'Emaco'), ('Pamoja school', 'Patwao Schools')], max_length=20),
        ),
    ]
