# Generated by Django 3.0.4 on 2020-04-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191118_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Phone_Number',
        ),
    ]
